package com.codefaucet.LoanMan.common;

public enum EnumModuleAccessId {

    CLIENT_VIEW,
    CLIENT_CREATE,
    CLIENT_EDIT,
    CLIENT_DELETE,
    CLIENT_RESTORE,

    CUTOFF_VIEW,
    CUTOFF_CREATE,
    CUTOFF_EDIT,
    CUTOFF_DELETE,
    CUTOFF_RESTORE,
    CUTOFF_POST,
    CUTOFF_UNPOST,

    CUTOFF_PROFILE_VIEW,
    CUTOFF_PROFILE_CREATE,
    CUTOFF_PROFILE_EDIT,
    CUTOFF_PROFILE_DELETE,
    CUTOFF_PROFILE_RESTORE,

    GROUP_VIEW,
    GROUP_CREATE,
    GROUP_EDIT,
    GROUP_DELETE,
    GROUP_RESTORE,

    GROUP_TYPE_VIEW,
    GROUP_TYPE_CREATE,
    GROUP_TYPE_EDIT,
    GROUP_TYPE_DELETE,
    GROUP_TYPE_RESTORE,

    LOAN_VIEW,
    LOAN_CREATE,
    LOAN_EDIT,
    LOAN_DELETE,
    LOAN_RESTORE,

    LOAN_TYPE_VIEW,
    LOAN_TYPE_CREATE,
    LOAN_TYPE_EDIT,
    LOAN_TYPE_DELETE,
    LOAN_TYPE_RESTORE,

    USER_VIEW,
    USER_CREATE,
    USER_EDIT,
    USER_DELETE,
    USER_RESTORE,

    USER_PROFILE_VIEW,
    USER_PROFILE_CREATE,
    USER_PROFILE_EDIT,
    USER_PROFILE_DELETE,
    USER_PROFILE_RESTORE,

    PAYMENT_VIEW,
    PAYMENT_CREATE,
    PAYMENT_EDIT,
    PAYMENT_DELETE,
    PAYMENT_RESTORE,
    
    SESSION_VIEW,
    SESSION_VIEW_DETAILS,
    SESSION_DEACTIVATE
    
}
